image:
  repository: postgres
  tag: "15"   # strongly recommended (MLflow compatible)

service:
  type: ClusterIP
  port: 5432

settings:
  # Use the existing secret for the postgres superuser
  existingSecret: postgres-admin

  # Explicitly define authentication method
  authMethod: md5

userDatabase:
  existingSecret: postgres-admin

  name:
    value: ds_db

  user:
    value: mlops

  password:
    secretKey: postgres-password

storage:
  requestedSize: 10Gi
  className: local-path
  accessModes:
    - ReadWriteOnce

metrics:
  enabled: false
